---
version: '2'
services:
  spring-docker-setup:
    image: com.rbiedrawa.docker.app/spring-docker-setup:0.0.1-SNAPSHOT
    container_name: spring-docker-setup
    restart: always
    ports:
      - 8080:8080
    environment:
      spring.profiles.active: docker